name:                decidable
version:             0.3.0.0
github:              "mstksg/decidable"
license:             BSD3
author:              "Justin Le"
maintainer:          "justin@jle.im"
copyright:           "(c) Justin Le 2018"
tested-with:         GHC >= 8.6

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Combinators for manipulating dependently-typed predicates.
category:            Dependent Types

description: |
  This library provides combinators and typeclasses for working and manipulating
  type-level predicates in Haskell, which are represented as matchable type-level
  functions @k ~> Type@ from the @singletons@ library.  See "Data.Type.Predicate"
  for a good starting point, and the documentation for 'Predicate' on how to
  define predicates.

ghc-options:
- -Wall
- -Wredundant-constraints
- -Wcompat
- -Werror=incomplete-patterns

dependencies:
- base >= 4.13 && < 5
- singletons >= 2.6
- vinyl
- microlens
- functor-products >= 0.1.1

library:
  source-dirs: src
